#!/bin/bash

case $1 in

	start)
		echo "Script starting..."
		/tmp/sleep-walking-server &
		;;
	stop)
		echo "Script stopped..."
		kill $(cat /tmp/sleep-walking-server.pid)
		;;
	*)
		echo "Usage sleep-walking start|stop" ; exit 1
		;;
esac
